version: '3'
services:
  statsd_client:
    # using statsd client, to create <prefix>.requests.incr.one.count - update prefix for naming
    # default metric type is count, incrementing one count at 1 sec interval
    container_name: statsd_client
    image: "min499/statsd_cm:0.1"
    environment:
      - STATSD_HOST=dd-agent
      - STATSD_PORT=8125
      - PREFIX=mytest
    depends_on:
      - dd-agent
  dd-agent:
    container_name: dd-agent
    image: "datadog/agent:7.45.1"
    environment:
    - DD_SITE=datadoghq.com
    - DD_API_KEY=<API_KEY>
    - DD_STATSD_FORWARD_HOST=telegraf
    - DD_STATSD_FORWARD_PORT=8125
    - DD_APM_ENABLED=false
    - DD_HOSTNAME=dd-ec2-test
    - DD_PROCESS_AGENT_ENABLED=true
    - DD_LOG_LEVEL=trace
    ## DOGSTATSD
    - DD_DOGSTATSD_PORT=8125
    - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    # - DD_DOGSTATSD_STATS_ENABLE=true
    # - DD_DOGSTATSD_ORIGIN_DETECTION_CLIENT=true
    ports:
      - 8125/udp # for Dogstatsd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro # LIVE PROCESSES
  telegraf:
    image: telegraf:1.26
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
volumes:
  influxdb_data: {}
